In [29]:
cv_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "CV MAE": [
        -lr_cv.best_score_,
        -rf_grid.best_score_,
        -gb_grid.best_score_
    ]
})

cv_results

               Model     CV MAE
0  Linear Regression  29.152686
1      Random Forest  23.216005
2  Gradient Boosting  26.145846

In [28]:
lr_cv.fit(X_train, y_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('categorical',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['admin1',
                                                                          'admin2',
                                                                          'market',
                                                                          'category',
                                                                          'commodity',
                                                                          'unit',
                                                                          'priceflag',
                                                                          'pricetype']),
                                                                        ('numerical',
                                                                         'passthrough',
                                                                         ['latitude',
                                                                          'longitude',
                                                                          'year',
                                                                          'month',
                                                                          'quarter'])])),
                                       ('model', LinearRegression())]),
             n_jobs=-1, param_grid={}, scoring='neg_mean_absolute_error',
             verbose=2)

In [27]:
lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)
lr_cv = GridSearchCV(
    estimator=lr_pipeline,
    param_grid={},
    cv=tscv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1,
    verbose=2
)

In [24]:
best_gb = gb_grid.best_estimator_

In [23]:
print("Best CV MAE:")
print(-gb_grid.best_score_)

Best CV MAE:
26.145846240367234

In [22]:
print("Best Gradient Boosting Parameters:")
print(gb_grid.best_params_)

Best Gradient Boosting Parameters:
{'model__learning_rate': 0.1, 'model__max_depth': 5, 'model__n_estimators': 100}

In [21]:
gb_grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('categorical',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['admin1',
                                                                          'admin2',
                                                                          'market',
                                                                          'category',
                                                                          'commodity',
                                                                          'unit',
                                                                          'priceflag',
                                                                          'pricetype']),
                                                                        ('numerical',
                                                                         'passthrough',
                                                                         ['latitude',
                                                                          'longitude',
                                                                          'year',
                                                                          'month',
                                                                          'quarter'])])),
                                       ('model',
                                        GradientBoostingRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [3, 5],
                         'model__n_estimators': [100]},
             scoring='neg_mean_absolute_error', verbose=2)

In [20]:
gb_grid = GridSearchCV(
    estimator=gb_pipeline,
    param_grid=gb_param_grid,
    cv=tscv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1,
    verbose=2
)

In [19]:
gb_param_grid = {
    "model__n_estimators": [100],
    "model__learning_rate": [0.05, 0.1],
    "model__max_depth": [3, 5]
}

In [18]:
gb_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            GradientBoostingRegressor(
                random_state=42
            )
        )
    ]
)

In [17]:
best_rf = rf_grid.best_estimator_

In [16]:
print("Best Random Forest Parameters:")
print(rf_grid.best_params_)
print("Best CV MAE:")
print(-rf_grid.best_score_)

Best Random Forest Parameters:
{'model__max_depth': None, 'model__max_features': 'sqrt', 'model__n_estimators': 100}
Best CV MAE:
23.21600489338577

In [15]:
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('categorical',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['admin1',
                                                                          'admin2',
                                                                          'market',
                                                                          'category',
                                                                          'commodity',
                                                                          'unit',
                                                                          'priceflag',
                                                                          'pricetype']),
                                                                        ('numerical',
                                                                         'passthrough',
                                                                         ['latitude',
                                                                          'longitude',
                                                                          'year',
                                                                          'month',
                                                                          'quarter'])])),
                                       ('model',
                                        RandomForestRegressor(n_jobs=-1,
                                                              random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [None, 20],
                         'model__max_features': ['sqrt'],
                         'model__n_estimators': [50, 100]},
             scoring='neg_mean_absolute_error', verbose=2)

In [14]:
rf_grid = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=rf_param_grid,
    cv=tscv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1,
    verbose=2
)

In [13]:
rf_param_grid = {
    "model__n_estimators": [50, 100],
    "model__max_depth": [None, 20],
    "model__max_features": ["sqrt"]
}

In [12]:
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestRegressor(
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

In [11]:
tscv = TimeSeriesSplit(n_splits=5)

In [10]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numeric_features
        )
    ]
)

In [9]:
numeric_features = [
    "latitude",
    "longitude",
    "year",
    "month",
    "quarter"
]

categorical_features = [
    "admin1",
    "admin2",
    "market",
    "category",
    "commodity",
    "unit",
    "priceflag",
    "pricetype"
]

In [7]:
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 193769
Testing rows: 48443

In [6]:
split_index = int(len(df) * 0.80)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [5]:
X = df.drop(columns=[
    "price",
    "market_id",
    "commodity_id",
    "currency",
    "usdprice",
    "date"
])

y = df["price"]

In [4]:
df = df.sort_values("date").reset_index(drop=True)
df[["date"]].head()
df[["date"]].tail()

             date
242207 2026-08-15
242208 2026-08-15
242209 2026-08-15
242210 2026-08-15
242211 2026-08-15

In [3]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["quarter"] = df["date"].dt.quarter

In [2]:
df = pd.read_csv("../data/original/wfp_food_prices_phl.csv")

df["date"] = pd.to_datetime(df["date"])

df.head()

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,167,14.6,120.98,cereals and tubers,"Rice (milled, superior)",593,KG,actual,Retail,PHP,20.00,0.49
1,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,167,14.6,120.98,cereals and tubers,"Rice (milled, superior)",593,KG,actual,Wholesale,PHP,18.35,0.45
2,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,167,14.6,120.98,cereals and tubers,"Rice (regular, milled)",80,KG,actual,Retail,PHP,18.00,0.44
3,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,167,14.6,120.98,cereals and tubers,"Rice (regular, milled)",80,KG,actual,Wholesale,PHP,16.35,0.40
4,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,167,14.6,120.98,"meat, fish and eggs",Meat (pork),140,KG,actual,Retail,PHP,105.37,2.60

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score